// Run this script with: node scripts/seed.js
// Make sure to set your MONGODB_URI in .env.local first

const mongoose = require('mongoose');
require('dotenv').config({ path: '.env.local' });

// ✅ Define the Car schema
const carSchema = new mongoose.Schema({
  name: String,
  brand: String,
  model: String,
  year: Number,
  pricePerDay: Number,
  category: String,
  transmission: String,
  fuelType: String,
  seats: Number,
  images: [String],
  features: [String],
  available: Boolean,
  location: String,
  description: String,
  rating: Number,
  reviews: Array,
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// ✅ Prevent OverwriteModelError if script runs multiple times
const Car = mongoose.models.Car || mongoose.model('Car', carSchema);

// ✅ Sample cars
const sampleCars = [
  {
    name: 'Honda City',
    brand: 'Honda',
    model: 'City ZX',
    year: 2023,
    pricePerDay: 1500,
    category: 'sedan',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://images.91wheels.com/assets/b_images/main/models/profile/profile1746428398.jpg?width=240&q=80'],
    features: ['AC', 'Power Steering', 'ABS', 'Airbags', 'Music System'],
    available: true,
    location: 'Delhi',
    description: 'Comfortable sedan perfect for city drives and long trips.',
    rating: 4.5,
  },
  {
    name: 'Maruti Swift',
    brand: 'Maruti Suzuki',
    model: 'Swift VXI',
    year: 2023,
    pricePerDay: 1200,
    category: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://imgd-ct.aeplcdn.com/664x415/n/3phi4ta_1508709.jpg?q=80'],
    features: ['AC', 'Power Windows', 'Central Locking', 'Music System'],
    available: true,
    location: 'Delhi',
    description: 'Fuel-efficient hatchback ideal for city commuting.',
    rating: 4.3,
  },
  {
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    model: 'Creta SX',
    year: 2023,
    pricePerDay: 2500,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    images: ['https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Creta/7695/1651645683867/front-left-side-47.jpg'],
    features: ['AC', 'Sunroof', 'Leather Seats', 'Touchscreen', 'Cruise Control'],
    available: true,
    location: 'Mumbai',
    description: 'Spacious SUV with premium features and comfortable ride.',
    rating: 4.7,
  },
  {
    name: 'Toyota Fortuner',
    brand: 'Toyota',
    model: 'Fortuner 4x4',
    year: 2023,
    pricePerDay: 4000,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 7,
    images: ['https://imgd.aeplcdn.com/664x374/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-20.jpeg?isig=0&q=80'],
    features: ['4WD', 'Leather Seats', 'Sunroof', 'Premium Sound', '7 Seats'],
    available: true,
    location: 'Bangalore',
    description: 'Luxury SUV perfect for family trips and adventures.',
    rating: 4.8,
  },
  {
    name: 'BMW 3 Series',
    brand: 'BMW',
    model: '320d Sport',
    year: 2023,
    pricePerDay: 6000,
    category: 'luxury',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800'],
    features: ['Leather Interior', 'Panoramic Sunroof', 'Premium Audio', 'Navigation'],
    available: true,
    location: 'Delhi',
    description: 'Premium luxury sedan with exceptional performance.',
    rating: 4.9,
  },
  {
    name: 'Mahindra Thar',
    brand: 'Mahindra',
    model: 'Thar LX',
    year: 2023,
    pricePerDay: 3000,
    category: 'suv',
    transmission: 'manual',
    fuelType: 'diesel',
    seats: 4,
    images: ['https://offers.caimahindra.com/uploads/product/Thar%20Aqua%20Marine.png'],
    features: ['4x4', 'Off-road Capable', 'Convertible Top', 'Adventure Ready'],
    available: true,
    location: 'Goa',
    description: 'Perfect for off-road adventures and beach trips.',
    rating: 4.6,
  },
  {
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3 Long Range',
    year: 2023,
    pricePerDay: 8000,
    category: 'luxury',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    images: ['https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800'],
    features: ['Autopilot', 'Electric', 'Premium Interior', 'Large Touchscreen'],
    available: true,
    location: 'Mumbai',
    description: 'Cutting-edge electric vehicle with autopilot features.',
    rating: 5.0,
  },
  {
    name: 'Kia Seltos',
    brand: 'Kia',
    model: 'Seltos GTX',
    year: 2023,
    pricePerDay: 2200,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIp3_QdRLH49Z3C6KWuxJNMrOz9Yn_s4EOJA&s'],
    features: ['Sunroof', 'Touchscreen', 'Ventilated Seats', 'Connected Car'],
    available: true,
    location: 'Pune',
    description: 'Modern SUV with advanced technology and comfort.',
    rating: 4.4,
  },
  {
    name: 'Mahindra Scorpio ',
    brand: 'Mahindra',
    model: 'Scorpio Classic',
    year: 2024,
    pricePerDay: 4200,
    category: 'suv',
    transmission: 'manual',
    fuelType: 'diesel',
    seats: 5,
    images: ['https://img.autocarindia.com/mmv_images/colors/20250714125759_Mahindra_Scorpio_Classic_Stealth_Black[1].jpg?w=640&q=75'],
    features: ['Rugged', 'Touchscreen', 'Off-road Capable', 'Adventure Car'],
    available: true,
    location: 'Delhi',
    description: 'Old school SUV.',
    rating: 4.8,
  },
  {
    name: 'Mahindra BE6',
    brand: 'Mahindra',
    model: 'BE6',
    year: 2025,
    pricePerDay: 6200,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'electric',
    seats: 5,
    images: ['https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/BE-6/12860/Mahindra-BE-6-Batman-Edition/1760012980715/front-left-side-47.jpg'],
    features: ['ADAS Level 2', 'Electric', 'Premium Interior', 'Connected Touchscreen'],
    available: true,
    location: 'Haryana',
    description: 'Stylish and futuristic all-electric SUV coupe built on the advanced INGLO platform, featuring powerful performance and a long range',
    rating: 4.6,
  },
  {
    name: 'Hyundai Verna',
    brand: 'Hyundai',
    model: 'Verna SX',
    year: 2023,
    pricePerDay: 3200,
    category: 'sedan',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://assets.thehansindia.com/h-upload/2023/03/21/1342810-hyundai-verna.webp'],
    features: ['ADAS Level 2', 'Futuristic design', 'Ventilated Seats', 'Premium technology and comfort'],
    available: true,
    location: 'Mumbai',
    description: 'A sharply styled, tech-rich mid-size sedan with turbo-petrol punch and Level-2 ADAS in India.',
    rating: 4.4,
  },
  {
    name: 'Kia Sonet',
    brand: 'Kia',
    model: 'Sonet HTX',
    year: 2022,
    pricePerDay: 2600,
    category: 'suv',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://img.autocarindia.com/ExtraImages/20230509112841_Sonet_aurochs.jpg?w=700&c=1'],
    features: ['Sunroof', 'Aggresive design', 'Ventilated Seats', 'Large Touchsreen'],
    available: true,
    location: 'Uttar Pradesh',
    description: 'A feature-rich, safety-boosted sub-4-metre compact SUV that blends bold styling with multiple powertrain options for urban India',
    rating: 4.3,
  },
    {
    name: 'Maruti Suzuki Wagon R',
    brand: 'Maruti Suzuki',
    model: 'Wagon R VXi+',
    year: 2024,
    pricePerDay: 900,
    category: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://www.varunmaruti.com/uploads/products/colors/wagonr-magma-grey.png'],
    features: ['7-inch Touchscreen', 'Rear Parking Camera', 'SmartPlay Infotainment'],
    available: true,
    location: 'Mumbai',
    description: 'Practical everyday city car with low running cost and high reliability.',
    rating: 4.5,
  },
  {
    name: 'Tata Nexon',
    brand: 'Tata Motors',
    model: 'Nexon XZ+',
    year: 2023,
    pricePerDay: 1800,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://imgd.aeplcdn.com/664x374/n/cw/ec/41645/tata-nexon-right-front-three-quarter3.jpeg?q=80'],
    features: ['5-Star Safety Rating', 'Connected Car Features', 'Terrain Response Mode'],
    available: true,
    location: 'Bangalore',
    description: 'Compact SUV with premium feel, strong build and safety credentials.',
    rating: 4.7,
  },
  {
    name: 'Maruti Suzuki Baleno',
    brand: 'Maruti Suzuki',
    model: 'Baleno Alpha',
    year: 2023,
    pricePerDay: 1400,
    category: 'hatchback',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://beyondautos.com/wp-content/uploads/2023/09/Suzuki-Balano.jpg'],
    features: ['Push Button Start', 'Sunroof', 'LED Headlamps', 'SmartPlay Studio'],
    available: true,
    location: 'Chennai',
    description: 'Premium hatchback offering spacious cabin and refined ride quality.',
    rating: 4.6,
  },
  {
    name: 'Maruti Suzuki Brezza',
    brand: 'Maruti Suzuki',
    model: 'Brezza Z+',
    year: 2022,
    pricePerDay: 2300,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://i.pinimg.com/736x/5a/9c/1d/5a9c1dde8d4377343b270c59dc068e8f.jpg'],
    features: ['Dual-Tone Roof', 'Multi-Function Display', 'SmartPlay Infotainment'],
    available: true,
    location: 'Hyderabad',
    description: 'Compact SUV with stylish design and good value for money.',
    rating: 4.4,
  },
  {
    name: 'Tata Punch',
    brand: 'Tata Motors',
    model: 'Punch Creative',
    year: 2024,
    pricePerDay: 1300,
    category: 'suv',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://www.livemint.com/lm-img/img/2024/10/04/600x338/camoedition_1728045253211_1728045261296.webp'],
    features: ['SUV Styling', 'High Ground Clearance', 'City Friendly Dimensions'],
    available: true,
    location: 'Pune',
    description: 'Micro-SUV ideal for city use, with SUV-look and manageable size.',
    rating: 4.5,
  },
  {
    name: 'Mahindra XUV 700',
    brand: 'Mahindra',
    model: 'XUV 700 AX7',
    year: 2024,
    pricePerDay: 3800,
    category: 'suv',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 7,
    images: ['https://auto.mahindra.com/on/demandware.static/-/Sites-mahindra-product-catalog/default/dw61abf05f/images/X700/XUV-700-New-Images/hires/AX7L_Dazzling_Silver_DT_1366x443.png'],
    features: ['7-Seater', 'Luxury SUV', 'High Level Performance', 'Panoramic Sunroof'],
    available: true,
    location: 'Kolkata',
    description: 'Luxury SUV with 7 seats and family-comfort.',
    rating: 4.6,
  },
  {
    name: 'Maruti Suzuki Ertiga',
    brand: 'Maruti Suzuki',
    model: 'Ertiga ZPluS',
    year: 2024,
    pricePerDay: 2000,
    category: 'suv',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 7,
    images: ['https://auto.hindustantimes.com/cms-images/marutisuzuki_ertiga/images/exterior_marutisuzuki-ertiga2022_front-left-side_1150x666.jpeg'],
    features: ['7-Seater Layout', 'Foldable Third Row', 'Rear AC Vents', 'SmartPlay Studio'],
    available: true,
    location: 'Ahmedabad',
    description: 'Versatile MPV suitable for family trips and group rides with comfort.',
    rating: 4.4,
  },
  {
    name: 'Maruti Suzuki Dzire',
    brand: 'Maruti Suzuki',
    model: 'Dzire ZXi',
    year: 2024,
    pricePerDay: 1200,
    category: 'sedan',
    transmission: 'manual',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://www.varunmaruti.com/uploads/products/colors/dzire-pearl-arctic-white.png'],
    features: ['Sedan Styling', 'Boot Space', 'AMT Option', 'SmartPlay Infotainment'],
    available: true,
    location: 'Chandigarh',
    description: 'Affordable premium compact sedan with good mileage and boot space.',
    rating: 4.5,
  },
  {
    name: 'Mercedes-Benz S-Class',
    brand: 'Mercedes-Benz',
    model: 'S580 4Matic',
    year: 2024,
    pricePerDay: 12000,
    category: 'luxury',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://static-cdn.cars24.com/prod/new-car-cms/Mercedes-Benz/S-Class/2024/04/02/a96eb352-eb35-479f-ab1b-9cf80bc46909-Mercedes-Benz_S-Class_Designo-Diamond-White.png'],
    features: ['Massage Seats', 'Burmeister Sound System', 'Rear Entertainment Screens', 'Ambient Lighting 64-Colour'],
    available: true,
    location: 'Mumbai',
    description: 'Flagship luxury sedan offering unmatched comfort, refinement and advanced tech.',
    rating: 4.9,
  },
  {
    name: 'BMW 7 Series',
    brand: 'BMW',
    model: '740d M Sport',
    year: 2024,
    pricePerDay: 11000,
    category: 'luxury',
    transmission: 'automatic',
    fuelType: 'diesel',
    seats: 5,
    images: ['https://www.bmw.co.th/content/dam/bmw/common/all-models/7-series/sedan/2025/bmw-7-series-sedan-modelfinder.png'],
    features: ['Executive Lounge Rear Seats', 'BMW Theatre Screen', 'Laser Headlights', 'M Sport Package'],
    available: true,
    location: 'Delhi',
    description: 'Premium driver-and-rear-passenger experience with sporty luxury and cutting-edge features.',
    rating: 4.8,
  },
  {
    name: 'Audi Q8',
    brand: 'Audi',
    model: 'Q8 55 TFSI',
    year: 2024,
    pricePerDay: 10000,
    category: 'luxury',
    transmission: 'automatic',
    fuelType: 'petrol',
    seats: 5,
    images: ['https://m.atcdn.co.uk/vms/media/0d7c8f9e7fb1449d87293de87aa17d57.jpg'],
    features: ['Matrix LED Headlights', 'Bang & Olufsen Sound System', 'Four-Zone Climate Control', 'Panoramic Sunroof'],
    available: true,
    location: 'Bengaluru',
    description: 'Luxury SUV combining style, performance and advanced tech in a bold package.',
    rating: 4.8,
  }




];

async function seedDatabase() {
  try {
    if (!process.env.MONGODB_URI) {
      throw new Error('❌ MONGODB_URI is not defined in .env.local');
    }

    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Car.deleteMany({});
    console.log('🗑️  Cleared existing cars');

    await Car.insertMany(sampleCars);
    console.log(`🚗 Inserted ${sampleCars.length} sample cars`);

    console.log('✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
